import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import api from "../api/axiosClient";
import toast from "react-hot-toast";

/* ─── Score helpers ─────────────────────────────────────── */
const SCORE_CFG = (s) =>
  s >= 0.4  ? { bar:"from-emerald-500 to-green-400",   ring:"ring-emerald-500/30",  badge:"bg-emerald-900/60 text-emerald-300 border-emerald-700",  label:"Strong Match",  dot:"bg-emerald-400" }
: s >= 0.25 ? { bar:"from-amber-500 to-yellow-400",    ring:"ring-amber-500/30",    badge:"bg-amber-900/60 text-amber-300 border-amber-700",        label:"Good Match",    dot:"bg-amber-400"   }
:             { bar:"from-blue-500 to-cyan-400",        ring:"ring-blue-500/30",     badge:"bg-blue-900/60 text-blue-300 border-blue-700",            label:"Partial Match", dot:"bg-blue-400"    };

const WORK_ICON = { Remote:"🌐", Hybrid:"🏢", "On-site":"📍" };

/* ─── PDF Download ──────────────────────────────────────── */
async function downloadPDF(letter, jobTitle, company) {
  try {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF({ unit:"mm", format:"a4" });
    const margin  = 20;
    const pageW   = doc.internal.pageSize.getWidth();
    const maxW    = pageW - margin * 2;

    // Header bar
    doc.setFillColor(2, 132, 199);           // brand-600
    doc.rect(0, 0, pageW, 28, "F");

    // Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Cover Letter", margin, 12);

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(`${jobTitle}  ·  ${company}`, margin, 20);

    // Date right-aligned
    const today = new Date().toLocaleDateString("en-IN", { day:"2-digit", month:"short", year:"numeric" });
    doc.text(today, pageW - margin, 20, { align:"right" });

    // Body
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");

    const lines = doc.splitTextToSize(letter, maxW);
    let y = 38;
    const lineH = 6;
    const pageH = doc.internal.pageSize.getHeight() - margin;

    for (const line of lines) {
      if (y + lineH > pageH) {
        doc.addPage();
        y = margin;
      }
      doc.text(line, margin, y);
      y += lineH;
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by AI Resume Agent", margin, doc.internal.pageSize.getHeight() - 8);

    const safeName = (jobTitle + "_" + company).replace(/\s+/g,"_").replace(/[^a-zA-Z0-9_]/g,"");
    doc.save(`CoverLetter_${safeName}.pdf`);
    toast.success("PDF downloaded! 📄");
  } catch (e) {
    toast.error("PDF generation failed.");
    console.error(e);
  }
}

/* ─── Cover Letter Box ──────────────────────────────────── */
function CoverLetterBox({ jobId, jobTitle, company }) {
  const [letter,  setLetter]  = useState("");
  const [loading, setLoading] = useState(false);
  const [copied,  setCopied]  = useState(false);

  const generate = async () => {
    setLoading(true); setLetter("");
    try {
      const res = await api.post(`/internships/${jobId}/cover-letter`);
      setLetter(res.data.cover_letter);
      toast.success("Cover letter ready! ✍️");
    } catch (err) {
      toast.error(err.response?.data?.detail || "Upload your resume from Dashboard first.");
    } finally { setLoading(false); }
  };

  const copy = () => {
    navigator.clipboard.writeText(letter);
    setCopied(true); toast.success("Copied to clipboard!");
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="mt-5 border-t border-white/5 pt-5">

      {/* Section label */}
      <div className="flex items-center gap-2 mb-4">
        <motion.div
          animate={{ rotate:[0,12,-12,0] }}
          transition={{ duration:2.5, repeat:Infinity, repeatDelay:4 }}
          className="w-8 h-8 rounded-lg bg-gradient-to-br from-purple-600 to-brand-600 flex items-center justify-center text-sm shadow-lg shadow-purple-500/30">
          ✍️
        </motion.div>
        <div>
          <p className="text-white font-semibold text-sm">Cover Letter Generator</p>
          <p className="text-gray-500 text-xs">AI-personalised from your resume</p>
        </div>
      </div>

      {/* Generate button (shown when no letter yet) */}
      <AnimatePresence mode="wait">
        {!letter && (
          <motion.div key="gen-btn"
            initial={{ opacity:0, y:8 }} animate={{ opacity:1, y:0 }}
            exit={{ opacity:0, y:-8 }} transition={{ duration:0.3 }}
          >
            <motion.button
              onClick={generate} disabled={loading}
              whileHover={!loading ? { scale:1.02, y:-1 } : {}}
              whileTap={!loading ? { scale:0.97 } : {}}
              className="relative w-full py-3 rounded-xl font-semibold text-sm overflow-hidden
                disabled:cursor-not-allowed disabled:opacity-60 group"
            >
              {/* Animated gradient bg */}
              <div className="absolute inset-0 bg-gradient-to-r from-violet-600 via-purple-600 to-brand-600
                group-hover:from-violet-500 group-hover:via-purple-500 group-hover:to-brand-500
                transition-all duration-300" />
              {/* Shimmer sweep */}
              {!loading && (
                <motion.div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/10 to-transparent -skew-x-12"
                  animate={{ x:["-200%","200%"] }}
                  transition={{ duration:2.5, repeat:Infinity, repeatDelay:1, ease:"easeInOut" }} />
              )}
              <span className="relative flex items-center justify-center gap-2 text-white drop-shadow">
                {loading ? (
                  <><motion.div animate={{ rotate:360 }} transition={{ duration:0.8, repeat:Infinity, ease:"linear" }}
                    className="w-4 h-4 border-2 border-white/40 border-t-white rounded-full"/>
                    Writing your letter...</>
                ) : <><span className="text-base">✨</span> Generate Cover Letter</>}
              </span>
            </motion.button>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Letter card */}
      <AnimatePresence>
        {letter && (
          <motion.div
            key="letter-card"
            initial={{ opacity:0, scale:0.96, y:16 }}
            animate={{ opacity:1, scale:1,    y:0 }}
            exit={{    opacity:0, scale:0.96, y:-8 }}
            transition={{ duration:0.45, ease:[0.22,1,0.36,1] }}
          >
            {/* Outer glow */}
            <motion.div
              animate={{ opacity:[0.4,0.7,0.4] }}
              transition={{ duration:3, repeat:Infinity }}
              className="absolute -inset-1 bg-gradient-to-r from-violet-600 via-purple-500 to-brand-600 rounded-2xl blur-lg pointer-events-none -z-10"
            />

            <div className="relative bg-gray-950 rounded-xl border border-purple-700/30 overflow-hidden shadow-2xl">

              {/* Document header */}
              <div className="bg-gradient-to-r from-violet-700 via-purple-700 to-brand-700 px-4 py-3 flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  {/* Traffic-light dots */}
                  {["bg-red-400","bg-yellow-400","bg-green-400"].map((c,i) => (
                    <motion.div key={i} className={"w-2.5 h-2.5 rounded-full " + c}
                      animate={{ scale:[1,1.15,1] }}
                      transition={{ duration:1.5, repeat:Infinity, delay:i*0.3 }} />
                  ))}
                  <span className="text-white/60 text-xs ml-1 font-mono">cover-letter.pdf</span>
                </div>
                <div className="flex items-center gap-1">
                  {/* Action buttons */}
                  {[
                    { icon: copied ? "✓":"📋", label: copied ? "Copied":"Copy",   action: copy,                                              active: copied, cls:"hover:bg-white/10" },
                    { icon:"⬇️",               label:"Download PDF",               action: () => downloadPDF(letter, jobTitle, company),       active: false,  cls:"hover:bg-white/10" },
                    { icon:"↻",                label:"Regenerate",                 action: () => setLetter(""),                               active: false,  cls:"hover:bg-white/10" },
                  ].map(({ icon, label, action, active, cls }) => (
                    <motion.button key={label} onClick={action}
                      whileHover={{ scale:1.08 }} whileTap={{ scale:0.92 }}
                      title={label}
                      className={"px-2 py-1 rounded-lg text-xs text-white/80 hover:text-white transition-all " + cls + (active ? " bg-white/20" : "")}>
                      {icon}
                    </motion.button>
                  ))}
                </div>
              </div>

              {/* Paper area */}
              <div className="relative">
                {/* Faint ruled lines background */}
                <div className="absolute inset-0 pointer-events-none"
                  style={{ backgroundImage:"repeating-linear-gradient(transparent, transparent 23px, rgba(255,255,255,0.02) 23px, rgba(255,255,255,0.02) 24px)" }} />

                <div className="relative px-5 py-4">
                  {/* Addressed to */}
                  <motion.div initial={{ opacity:0 }} animate={{ opacity:1 }} transition={{ delay:0.2 }}
                    className="flex justify-between items-start mb-3 pb-3 border-b border-gray-800">
                    <div>
                      <p className="text-gray-400 text-xs">Applying for</p>
                      <p className="text-white text-xs font-semibold">{jobTitle}</p>
                      <p className="text-purple-400 text-xs">{company}</p>
                    </div>
                    <div className="text-right">
                      <p className="text-gray-500 text-xs">{new Date().toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})}</p>
                    </div>
                  </motion.div>

                  {/* Letter text */}
                  <motion.pre
                    initial={{ opacity:0 }} animate={{ opacity:1 }} transition={{ delay:0.3 }}
                    className="text-gray-300 text-xs leading-6 whitespace-pre-wrap font-sans max-h-56 overflow-y-auto pr-2
                      scrollbar-thin scrollbar-thumb-gray-700 scrollbar-track-transparent">
                    {letter}
                  </motion.pre>
                </div>
              </div>

              {/* Bottom action bar */}
              <motion.div
                initial={{ opacity:0, y:8 }} animate={{ opacity:1, y:0 }} transition={{ delay:0.4 }}
                className="border-t border-gray-800 px-4 py-3 flex gap-2 bg-gray-900/60"
              >
                <motion.button onClick={copy}
                  whileHover={{ scale:1.03, y:-1 }} whileTap={{ scale:0.96 }}
                  className={"flex-1 py-2 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition-all border " +
                    (copied
                      ? "bg-green-700 border-green-600 text-white"
                      : "bg-gray-800 border-gray-700 text-gray-300 hover:border-purple-500 hover:text-purple-300")}>
                  {copied ? "✓ Copied!" : "📋 Copy Text"}
                </motion.button>

                <motion.button onClick={() => downloadPDF(letter, jobTitle, company)}
                  whileHover={{ scale:1.03, y:-1 }} whileTap={{ scale:0.96 }}
                  className="flex-1 py-2 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition-all
                    bg-gradient-to-r from-brand-700 to-purple-700 hover:from-brand-600 hover:to-purple-600
                    text-white border border-brand-600/50 shadow-lg shadow-brand-500/20 btn-glow">
                  ⬇️ Download PDF
                </motion.button>
              </motion.div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

/* ─── Apply Button ──────────────────────────────────────── */
function ApplyButton({ jobId, jobTitle, company }) {
  const [applied, setApplied]   = useState(false);
  const [loading, setLoading]   = useState(false);

  const handleApply = async () => {
    setLoading(true);
    try {
      await api.post(`/internships/${jobId}/apply`);
      setApplied(true);
      toast.success(`Applied to ${jobTitle} at ${company}! 🎉`);
    } catch (err) {
      const msg = err.response?.data?.detail || "Failed to apply.";
      if (msg.includes("already applied")) {
        setApplied(true);
        toast.error(msg);
      } else {
        toast.error(msg);
      }
    } finally { setLoading(false); }
  };

  return (
    <motion.div className="mt-4" initial={{ opacity:0, y:6 }} animate={{ opacity:1, y:0 }} transition={{ delay:0.15 }}>
      <motion.button
        onClick={handleApply}
        disabled={loading || applied}
        whileHover={!applied && !loading ? { scale:1.02, y:-1 } : {}}
        whileTap={!applied && !loading ? { scale:0.97 } : {}}
        className={"w-full py-2.5 rounded-xl font-semibold text-sm flex items-center justify-center gap-2 transition-all border " +
          (applied
            ? "bg-green-900/40 border-green-700/50 text-green-400 cursor-default"
            : "bg-gradient-to-r from-brand-600 to-emerald-600 hover:from-brand-500 hover:to-emerald-500 text-white border-brand-500/30 shadow-lg shadow-brand-500/20 btn-glow disabled:opacity-60 disabled:cursor-not-allowed")}
      >
        {loading ? (
          <><motion.div animate={{ rotate:360 }} transition={{ duration:0.8, repeat:Infinity, ease:"linear" }}
            className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full"/> Applying…</>
        ) : applied ? (
          <><span>✓</span> Applied</>
        ) : (
          <><span>🚀</span> Apply Now</>
        )}
      </motion.button>
    </motion.div>
  );
}

/* ─── Main RagMatchCard ─────────────────────────────────── */
const SCORE_CONFIG = SCORE_CFG;

export default function RagMatchCard({ matches }) {
  const [activeId, setActiveId] = useState(null);
  const toggle = (id) => setActiveId(p => p === id ? null : id);

  return (
    <div className="space-y-3">
      {/* Header */}
      <motion.div className="flex items-center justify-between"
        initial={{ opacity:0, y:-10 }} animate={{ opacity:1, y:0 }}>
        <div>
          <h3 className="font-bold text-white flex items-center gap-2 text-base">
            <span>🎯</span> AI Internship Matches
          </h3>
          <p className="text-gray-500 text-xs mt-0.5">
            {matches.length} best matches · click any card for details & cover letter
          </p>
        </div>
        <motion.span
          animate={{ opacity:[1,0.5,1] }} transition={{ duration:2.5, repeat:Infinity }}
          className="text-xs bg-brand-900/50 text-brand-300 border border-brand-700/50 px-2 py-1 rounded-full font-medium">
          ⚡ RAG Powered
        </motion.span>
      </motion.div>

      {/* Cards */}
      {matches.map((match, idx) => {
        const cfg    = SCORE_CFG(match.composite_score);
        const pct    = Math.round(match.composite_score * 100);
        const isOpen = activeId === match.job_id;

        return (
          <motion.div key={match.job_id}
            initial={{ opacity:0, y:20 }} animate={{ opacity:1, y:0 }}
            transition={{ delay: idx * 0.08, duration:0.4, ease:[0.22,1,0.36,1] }}
          >
            <motion.div
              animate={isOpen
                ? { boxShadow:"0 0 40px rgba(14,165,233,0.12), 0 0 0 1px rgba(14,165,233,0.2)" }
                : { boxShadow:"none" }}
              transition={{ duration:0.3 }}
              className="rounded-2xl overflow-hidden"
            >
              <div className={"border rounded-2xl transition-colors duration-300 overflow-hidden " +
                (isOpen ? "border-gray-600 bg-gray-900" : "border-gray-700/60 bg-gray-900/60 hover:border-gray-600 hover:bg-gray-900/80")}>

                {/* Coloured top stripe when open */}
                <AnimatePresence>
                  {isOpen && (
                    <motion.div key="stripe"
                      initial={{ scaleX:0, opacity:0 }} animate={{ scaleX:1, opacity:1 }}
                      exit={{    scaleX:0, opacity:0 }}
                      style={{ transformOrigin:"left" }}
                      className={"h-0.5 bg-gradient-to-r " + cfg.bar}
                      transition={{ duration:0.35 }} />
                  )}
                </AnimatePresence>

                {/* ── Clickable header ── */}
                <motion.div className="p-4 cursor-pointer select-none"
                  onClick={() => toggle(match.job_id)}
                  whileHover={{ backgroundColor:"rgba(255,255,255,0.02)" }}
                >
                  <div className="flex items-start gap-3">
                    {/* Rank badge */}
                    <motion.div
                      className={"w-9 h-9 rounded-xl flex-shrink-0 flex items-center justify-center font-bold text-white bg-gradient-to-br shadow-lg " + cfg.bar}
                      animate={isOpen ? { rotate:[0,8,-8,0], scale:[1,1.1,1] } : {}}
                      transition={{ duration:0.5, type:"spring" }}>
                      {idx + 1}
                    </motion.div>

                    <div className="flex-1 min-w-0">
                      <div className="flex items-start justify-between gap-2">
                        <div className="min-w-0">
                          <h4 className="font-semibold text-white text-sm leading-snug truncate">{match.title}</h4>
                          <p className="text-gray-400 text-xs mt-0.5">{match.company}
                            {match.work_mode && <span className="ml-2 text-gray-600">· {WORK_ICON[match.work_mode]} {match.work_mode}</span>}
                            {match.duration  && <span className="ml-2 text-gray-600">· ⏱ {match.duration}</span>}
                          </p>
                        </div>
                        <div className="flex items-center gap-2 flex-shrink-0">
                          {/* Live dot */}
                          <motion.div className={"w-2 h-2 rounded-full flex-shrink-0 " + cfg.dot}
                            animate={{ scale:[1,1.4,1], opacity:[1,0.5,1] }}
                            transition={{ duration:1.8, repeat:Infinity, delay: idx * 0.2 }} />
                          <span className={"text-xs px-2 py-0.5 rounded-full border font-medium " + cfg.badge}>{cfg.label}</span>
                          <motion.span animate={{ rotate: isOpen ? 90 : 0 }} transition={{ duration:0.25 }}
                            className="text-gray-500 text-lg leading-none">›</motion.span>
                        </div>
                      </div>

                      {/* Score bar */}
                      <div className="mt-2.5">
                        <div className="flex justify-between text-xs mb-1 text-gray-500">
                          <span>Compatibility</span>
                          <span className="font-bold text-white">{pct}%</span>
                        </div>
                        <div className="h-1.5 bg-gray-800 rounded-full overflow-hidden">
                          <motion.div className={"h-full rounded-full bg-gradient-to-r " + cfg.bar}
                            initial={{ width:0 }}
                            animate={{ width: Math.min(pct * 2, 100) + "%" }}
                            transition={{ duration:1, delay: idx*0.1+0.2, ease:"easeOut" }} />
                        </div>
                      </div>

                      {/* Matched skill chips (collapsed preview) */}
                      {!isOpen && match.matched_skills?.length > 0 && (
                        <motion.div className="flex flex-wrap gap-1 mt-2"
                          initial={{ opacity:0 }} animate={{ opacity:1 }} transition={{ delay:0.3 }}>
                          {match.matched_skills.slice(0,4).map(s => (
                            <span key={s} className="text-xs px-1.5 py-0.5 rounded-md bg-green-900/40 text-green-400 border border-green-800/50">✓ {s}</span>
                          ))}
                          {match.matched_skills.length > 4 && (
                            <span className="text-xs px-1.5 py-0.5 rounded-md bg-gray-800 text-gray-500">+{match.matched_skills.length-4}</span>
                          )}
                        </motion.div>
                      )}
                    </div>
                  </div>
                </motion.div>

                {/* ── Expanded section ── */}
                <AnimatePresence initial={false}>
                  {isOpen && (
                    <motion.div
                      initial={{ height:0, opacity:0 }}
                      animate={{ height:"auto", opacity:1 }}
                      exit={{    height:0, opacity:0 }}
                      transition={{ duration:0.4, ease:[0.22,1,0.36,1] }}
                      className="overflow-hidden"
                    >
                      <div className="px-4 pb-5 space-y-4 border-t border-gray-800">
                        {/* All skills */}
                        {match.matched_skills?.length > 0 && (
                          <motion.div className="pt-4"
                            initial={{ opacity:0, y:6 }} animate={{ opacity:1, y:0 }} transition={{ delay:0.1 }}>
                            <p className="text-xs text-gray-500 font-medium mb-2 uppercase tracking-wide">Your Matching Skills</p>
                            <div className="flex flex-wrap gap-1.5">
                              {match.matched_skills.map((s, i) => (
                                <motion.span key={s}
                                  initial={{ opacity:0, scale:0.7 }} animate={{ opacity:1, scale:1 }}
                                  transition={{ delay: 0.12 + i*0.04, type:"spring", stiffness:250 }}
                                  whileHover={{ scale:1.08 }}
                                  className="text-xs px-2.5 py-1 rounded-lg bg-green-900/40 text-green-300 border border-green-800/60 cursor-default">
                                  ✓ {s}
                                </motion.span>
                              ))}
                            </div>
                          </motion.div>
                        )}

                        {/* Apply button */}
                        <ApplyButton jobId={match.job_id} jobTitle={match.title} company={match.company} />

                        {/* Cover letter section */}
                        <motion.div initial={{ opacity:0 }} animate={{ opacity:1 }} transition={{ delay:0.2 }}>
                          <CoverLetterBox jobId={match.job_id} jobTitle={match.title} company={match.company} />
                        </motion.div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            </motion.div>
          </motion.div>
        );
      })}
    </div>
  );
}