import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { motion, AnimatePresence } from "framer-motion";
import api from "../api/axiosClient";
import toast from "react-hot-toast";

async function downloadPDF(letter, jobTitle, company) {
  try {
    const { jsPDF } = await import("jspdf");
    const doc  = new jsPDF({ unit:"mm", format:"a4" });
    const mX   = 20;
    const pageW = doc.internal.pageSize.getWidth();
    const maxW  = pageW - mX * 2;
    doc.setFillColor(2,132,199);
    doc.rect(0,0,pageW,28,"F");
    doc.setTextColor(255,255,255);
    doc.setFontSize(15); doc.setFont("helvetica","bold");
    doc.text("Cover Letter",mX,12);
    doc.setFontSize(9);  doc.setFont("helvetica","normal");
    doc.text(`${jobTitle}  ·  ${company}`,mX,20);
    const today = new Date().toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"});
    doc.text(today, pageW-mX, 20, { align:"right" });
    doc.setTextColor(30,30,30); doc.setFontSize(11);
    const lines = doc.splitTextToSize(letter, maxW);
    let y = 38;
    for (const line of lines) {
      if (y+6 > doc.internal.pageSize.getHeight()-mX) { doc.addPage(); y=mX; }
      doc.text(line,mX,y); y+=6;
    }
    doc.setFontSize(8); doc.setTextColor(150,150,150);
    doc.text("Generated by AI Resume Agent", mX, doc.internal.pageSize.getHeight()-8);
    const safe = (jobTitle+"_"+company).replace(/\s+/g,"_").replace(/[^a-zA-Z0-9_]/g,"");
    doc.save(`CoverLetter_${safe}.pdf`);
    toast.success("PDF downloaded! 📄");
  } catch { toast.error("PDF generation failed."); }
}

export default function CoverLetterPage() {
  const navigate = useNavigate();
  const [internships, setInternships] = useState([]);
  const [selected,    setSelected]    = useState(null);
  const [letter,      setLetter]      = useState("");
  const [loading,     setLoading]     = useState(false);
  const [copied,      setCopied]      = useState(false);
  const [fetching,    setFetching]    = useState(true);

  useEffect(() => {
    api.get("/internships")
      .then(r => setInternships(r.data))
      .catch(() => toast.error("Could not load internships."))
      .finally(() => setFetching(false));
  }, []);

  const generate = async () => {
    if (!selected) return toast.error("Select an internship first.");
    setLoading(true); setLetter("");
    try {
      const res = await api.post(`/internships/${selected.id}/cover-letter`);
      setLetter(res.data.cover_letter);
      toast.success("Cover letter ready! ✍️");
    } catch (err) { toast.error(err.response?.data?.detail || "Upload resume from Dashboard first."); }
    finally { setLoading(false); }
  };

  const copy = () => {
    navigator.clipboard.writeText(letter);
    setCopied(true); toast.success("Copied!");
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-4xl mx-auto px-4 py-8 space-y-6">

      {/* Header */}
      <motion.div initial={{ opacity:0, y:-20 }} animate={{ opacity:1, y:0 }} transition={{ duration:0.5 }}>
        <div className="flex items-center gap-3 mb-1">
          <motion.button whileHover={{ x:-4 }} onClick={() => navigate("/")}
            className="text-gray-500 hover:text-white transition text-sm">← Back</motion.button>
          <span className="text-gray-700">·</span>
          <span className="text-gray-500 text-sm">Cover Letter Generator</span>
        </div>
        <h1 className="text-3xl font-black text-white">
          ✍️ <span className="gradient-text">Cover Letter</span> Generator
        </h1>
        <p className="text-gray-400 text-sm mt-1">
          Select an internship below, then generate a personalised letter from your resume.
        </p>
      </motion.div>

      <div className="grid grid-cols-1 lg:grid-cols-5 gap-5">

        {/* Left — Internship picker */}
        <div className="lg:col-span-2 space-y-3">
          <motion.p initial={{ opacity:0 }} animate={{ opacity:1 }} transition={{ delay:0.1 }}
            className="text-xs text-gray-500 font-semibold uppercase tracking-widest">
            Select Internship
          </motion.p>

          {fetching ? (
            <div className="space-y-2">
              {[...Array(4)].map((_,i) => (
                <motion.div key={i} initial={{ opacity:0 }} animate={{ opacity:1 }} transition={{ delay:i*0.08 }}
                  className="h-16 rounded-xl shimmer" />
              ))}
            </div>
          ) : (
            <div className="space-y-2 max-h-[70vh] overflow-y-auto pr-1
              [&::-webkit-scrollbar]:w-1 [&::-webkit-scrollbar-thumb]:bg-gray-700 [&::-webkit-scrollbar-thumb]:rounded-full">
              {internships.map((job, i) => {
                const isActive = selected?.id === job.id;
                return (
                  <motion.div key={job.id}
                    initial={{ opacity:0, x:-16 }} animate={{ opacity:1, x:0 }}
                    transition={{ delay: i*0.05, duration:0.35 }}
                    onClick={() => { setSelected(job); setLetter(""); }}
                    whileHover={{ x:3 }} whileTap={{ scale:0.98 }}
                    className={"relative rounded-xl border p-3.5 cursor-pointer transition-all duration-200 overflow-hidden card-shine " +
                      (isActive
                        ? "border-brand-600/60 bg-brand-900/20 shadow-lg shadow-brand-500/10"
                        : "border-gray-700/60 bg-gray-900/50 hover:border-gray-600")}
                  >
                    {isActive && (
                      <motion.div layoutId="selector"
                        className="absolute left-0 top-0 bottom-0 w-0.5 bg-brand-400" />
                    )}
                    <div className="flex items-start justify-between gap-2">
                      <div className="min-w-0">
                        <p className={"font-semibold text-xs leading-snug " + (isActive?"text-white":"text-gray-300")}>{job.title}</p>
                        <p className={"text-xs mt-0.5 " + (isActive?"text-brand-400":"text-gray-500")}>{job.company}</p>
                      </div>
                      {isActive && (
                        <motion.div initial={{ scale:0 }} animate={{ scale:1 }} transition={{ type:"spring", stiffness:300 }}
                          className="w-5 h-5 rounded-full bg-brand-500 flex items-center justify-center text-white text-xs flex-shrink-0">✓</motion.div>
                      )}
                    </div>
                    {job.work_mode && (
                      <p className="text-xs text-gray-600 mt-1.5">
                        {{Remote:"🌐",Hybrid:"🏢","On-site":"📍"}[job.work_mode]} {job.work_mode}
                        {job.duration && ` · ⏱ ${job.duration}`}
                      </p>
                    )}
                  </motion.div>
                );
              })}
            </div>
          )}
        </div>

        {/* Right — Generator */}
        <div className="lg:col-span-3">
          <AnimatePresence mode="wait">
            {!selected ? (
              <motion.div key="empty"
                className="glass rounded-2xl flex flex-col items-center justify-center p-16 text-center border border-dashed border-gray-800 min-h-64"
                initial={{ opacity:0 }} animate={{ opacity:1 }} exit={{ opacity:0 }}>
                <motion.div className="text-5xl mb-4 opacity-20"
                  animate={{ y:[0,-10,0], rotate:[0,8,-8,0] }}
                  transition={{ duration:4, repeat:Infinity, ease:"easeInOut" }}>✍️</motion.div>
                <p className="text-gray-600 font-semibold">Pick an internship</p>
                <p className="text-gray-700 text-sm mt-1">Your cover letter will appear here</p>
              </motion.div>
            ) : (
              <motion.div key={selected.id} className="space-y-4"
                initial={{ opacity:0, x:20 }} animate={{ opacity:1, x:0 }}
                exit={{ opacity:0, x:-20 }} transition={{ duration:0.35 }}>

                {/* Selected job header */}
                <div className="glass rounded-2xl p-4 flex items-center gap-4">
                  <motion.div initial={{ scale:0 }} animate={{ scale:1 }} transition={{ type:"spring", stiffness:250 }}
                    className="w-10 h-10 rounded-xl bg-gradient-to-br from-brand-600 to-purple-600 flex items-center justify-center text-lg shadow-lg shadow-brand-500/20">
                    🏢
                  </motion.div>
                  <div>
                    <p className="text-white font-semibold text-sm">{selected.title}</p>
                    <p className="text-gray-400 text-xs">{selected.company}</p>
                  </div>
                </div>

                {/* Generate button */}
                {!letter && (
                  <motion.button onClick={generate} disabled={loading}
                    initial={{ opacity:0, y:8 }} animate={{ opacity:1, y:0 }}
                    whileHover={!loading?{scale:1.02,y:-1}:{}} whileTap={!loading?{scale:0.97}:{}}
                    className="relative w-full py-3 rounded-xl font-bold text-white text-sm overflow-hidden disabled:opacity-60 disabled:cursor-not-allowed">
                    <div className="absolute inset-0 bg-gradient-to-r from-violet-600 via-purple-600 to-brand-600 hover:from-violet-500 hover:via-purple-500 hover:to-brand-500 transition-all" />
                    {!loading && (
                      <motion.div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/10 to-transparent -skew-x-12"
                        animate={{ x:["-200%","200%"] }} transition={{ duration:2.5, repeat:Infinity, repeatDelay:0.5 }} />
                    )}
                    <span className="relative flex items-center justify-center gap-2">
                      {loading
                        ? <><motion.div animate={{ rotate:360 }} transition={{ duration:0.8, repeat:Infinity, ease:"linear" }}
                            className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full"/>Writing your letter…</>
                        : <><span>✨</span> Generate Cover Letter</>}
                    </span>
                  </motion.button>
                )}

                {/* Letter card */}
                <AnimatePresence>
                  {letter && (
                    <motion.div
                      initial={{ opacity:0, scale:0.96, y:16 }}
                      animate={{ opacity:1, scale:1,    y:0  }}
                      exit={{    opacity:0, scale:0.94, y:-8 }}
                      transition={{ duration:0.45, ease:[0.22,1,0.36,1] }}
                      className="relative"
                    >
                      {/* Glow */}
                      <motion.div animate={{ opacity:[0.3,0.6,0.3] }} transition={{ duration:3, repeat:Infinity }}
                        className="absolute -inset-1 bg-gradient-to-r from-violet-600 via-purple-500 to-brand-600 rounded-2xl blur-lg pointer-events-none -z-10" />

                      <div className="relative bg-gray-950 rounded-xl border border-purple-700/30 overflow-hidden shadow-2xl">
                        {/* Window chrome */}
                        <div className="bg-gradient-to-r from-violet-700 via-purple-700 to-brand-700 px-4 py-2.5 flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            {["bg-red-400","bg-yellow-400","bg-green-400"].map((c,i)=>(
                              <motion.div key={i} className={"w-2.5 h-2.5 rounded-full "+c}
                                animate={{ scale:[1,1.2,1] }} transition={{ duration:1.5, repeat:Infinity, delay:i*0.3 }}/>
                            ))}
                            <span className="text-white/50 text-xs ml-1 font-mono">cover-letter.pdf</span>
                          </div>
                          <div className="flex gap-1">
                            {[
                              { icon:copied?"✓":"📋", title:"Copy",    action:copy },
                              { icon:"⬇️",            title:"PDF",     action:()=>downloadPDF(letter,selected.title,selected.company) },
                              { icon:"↻",             title:"Redo",    action:()=>setLetter("") },
                            ].map(({icon,title,action})=>(
                              <motion.button key={title} onClick={action} title={title}
                                whileHover={{scale:1.12}} whileTap={{scale:0.9}}
                                className="px-2 py-1 rounded-lg text-xs text-white/70 hover:text-white hover:bg-white/10 transition">
                                {icon}
                              </motion.button>
                            ))}
                          </div>
                        </div>

                        {/* Ruled paper body */}
                        <div className="relative px-5 py-4"
                          style={{ backgroundImage:"repeating-linear-gradient(transparent,transparent 23px,rgba(255,255,255,0.02) 23px,rgba(255,255,255,0.02) 24px)" }}>
                          <motion.div initial={{ opacity:0 }} animate={{ opacity:1 }} transition={{ delay:0.15 }}
                            className="flex justify-between text-xs mb-3 pb-2 border-b border-gray-800">
                            <div>
                              <p className="text-white font-semibold">{selected.title}</p>
                              <p className="text-purple-400">{selected.company}</p>
                            </div>
                            <p className="text-gray-500">{new Date().toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})}</p>
                          </motion.div>
                          <motion.pre initial={{ opacity:0 }} animate={{ opacity:1 }} transition={{ delay:0.25 }}
                            className="text-gray-300 text-xs leading-6 whitespace-pre-wrap font-sans max-h-72 overflow-y-auto pr-1
                              [&::-webkit-scrollbar]:w-1 [&::-webkit-scrollbar-thumb]:bg-gray-700 [&::-webkit-scrollbar-thumb]:rounded-full">
                            {letter}
                          </motion.pre>
                        </div>

                        {/* Action bar */}
                        <motion.div initial={{ opacity:0,y:8 }} animate={{ opacity:1,y:0 }} transition={{ delay:0.35 }}
                          className="border-t border-gray-800 px-4 py-3 flex gap-2 bg-gray-900/60">
                          <motion.button onClick={copy}
                            whileHover={{ scale:1.03,y:-1 }} whileTap={{ scale:0.96 }}
                            className={"flex-1 py-2 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 border transition-all "+
                              (copied?"bg-green-700 border-green-600 text-white":"bg-gray-800 border-gray-700 text-gray-300 hover:border-purple-500 hover:text-purple-300")}>
                            {copied?"✓ Copied!":"📋 Copy Text"}
                          </motion.button>
                          <motion.button onClick={()=>downloadPDF(letter,selected.title,selected.company)}
                            whileHover={{ scale:1.03,y:-1 }} whileTap={{ scale:0.96 }}
                            className="flex-1 py-2 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition-all
                              bg-gradient-to-r from-brand-700 to-purple-700 hover:from-brand-600 hover:to-purple-600
                              text-white border border-brand-600/50 shadow-lg shadow-brand-500/20 btn-glow">
                            ⬇️ Download PDF
                          </motion.button>
                          <motion.button onClick={()=>setLetter("")}
                            whileHover={{ scale:1.06 }} whileTap={{ scale:0.93 }}
                            className="px-3 py-2 rounded-lg text-xs bg-gray-800 border border-gray-700 text-gray-400 hover:text-white hover:bg-gray-700 transition">
                            ↻
                          </motion.button>
                        </motion.div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
}